INSERT INTO BOOKMARK (URL, DESCRIPTION, REG_DATE) VALUES ('http://www.google.com', 'google', NOW());
INSERT INTO BOOKMARK (URL, DESCRIPTION, REG_DATE) VALUES ('http://www.google.com', 'google2', NOW());
INSERT INTO BOOKMARK (URL, DESCRIPTION, REG_DATE) VALUES ('http://www.google.com', 'google3', NOW());
INSERT INTO BOOKMARK (URL, DESCRIPTION, REG_DATE) VALUES ('http://www.naver.com', 'naver', NOW());
INSERT INTO BOOKMARK (URL, DESCRIPTION, REG_DATE) VALUES ('http://www.daum.net', 'daum', NOW());
INSERT INTO BOOKMARK (URL, DESCRIPTION, REG_DATE) VALUES ('https://www.youtube.com/', 'youtube', NOW());

INSERT INTO TAGS (NAME) VALUES ('portal');
INSERT INTO TAGS (NAME) VALUES ('movie');
INSERT INTO TAGS (NAME) VALUES ('multi');
INSERT INTO TAGS (NAME) VALUES ('favorite');
INSERT INTO TAGS (NAME) VALUES ('dev');

INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('1', '1');   --google portal
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('1', '4');   --google favorite
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('2', '3');   --google2 multi
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('2', '5');   --google2 dev
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('2', '1');   --google2 portal
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('3', '3');   --google3 multi
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('3', '5');   --google3 dev
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('4', '1');   --naver portal
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('5', '1');   --daum portal
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('6', '2');   --youtube movie
INSERT INTO BOOKMARK_TAGS (BOOKMARK_UID, TAGS_UID) VALUES ('6', '4');   --youtube favorite